#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=4
#SBATCH --gpus=1
#SBATCH --job-name=ONXX_VGGT
#SBATCH --ntasks=1
#SBATCH --time=05:30:00
#SBATCH --mem=122000M
#SBATCH --output=outfiles/ONXX_VGGT_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1
#module load CUDA/11.8.0


export WANDB_API_KEY="5d3260b21e8729601f20bfe817abc713a0dcc047"
export WANDB_ENTITY="nlp-squad"
export WANDB_PROJECT="Geo_Octo"


source activate onnx-build

srun -u python export_vggt.py