#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=4
#SBATCH --gpus=1
#SBATCH --job-name=Map_Episode_Tasks
#SBATCH --ntasks=1
#SBATCH --time=05:30:00
#SBATCH --mem=8000M
#SBATCH --output=outfiles/map_episode_to_task_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1
#module load CUDA/11.8.0


export WANDB_API_KEY="5d3260b21e8729601f20bfe817abc713a0dcc047"
export WANDB_ENTITY="nlp-squad"
export WANDB_PROJECT="Geo_Octo"


source activate octo-libero-eval

export PATH=\"$CUDA_NVCC_BIN:$PATH\"
export LD_LIBRARY_PATH=\"$NVRTC_LIB_DIR:$CONDA_PREFIX/lib:$LD_LIBRARY_PATH\"
export PYTHONPATH="/gpfs/home4/pkarageorgis/geo_octo:/gpfs/home4/pkarageorgis/geo_octo/LIBERO:/gpfs/home4/pkarageorgis/geo_octo/octo:$PYTHONPATH"


# GPU diagnostics (runs on the allocated GPU node)
srun -n 1 python - <<'PY'
import os, jax, torch
print('CUDA_VISIBLE_DEVICES=', os.environ.get('CUDA_VISIBLE_DEVICES'))
print('JAX:', jax.default_backend(), jax.devices())
print('Torch CUDA:', torch.version.cuda)
PY

srun -n 1 python -u /gpfs/home4/pkarageorgis/geo_octo/evaluation/scripts/build_task_to_episode_map.py \
  --dataset_dir /gpfs/home4/pkarageorgis/geo_octo/libero_datasets/libero_spatial_no_noops/1.0.0 \
  --out /gpfs/home4/pkarageorgis/geo_octo/evaluation/task_to_episode_map/libero_spatial_no_noops_1.0.0.json

srun -n 1 python -u /gpfs/home4/pkarageorgis/geo_octo/evaluation/scripts/build_task_to_episode_map.py \
  --dataset_dir /gpfs/home4/pkarageorgis/geo_octo/libero_datasets/libero_object_no_noops/1.0.0 \
  --out /gpfs/home4/pkarageorgis/geo_octo/evaluation/task_to_episode_map/libero_object_no_noops_1.0.0.json

srun -n 1 python -u /gpfs/home4/pkarageorgis/geo_octo/evaluation/scripts/build_task_to_episode_map.py \
  --dataset_dir /gpfs/home4/pkarageorgis/geo_octo/libero_datasets/libero_goal_no_noops/1.0.0 \
  --out /gpfs/home4/pkarageorgis/geo_octo/evaluation/task_to_episode_map/libero_goal_no_noops_1.0.0.json

srun -n 1 python -u /gpfs/home4/pkarageorgis/geo_octo/evaluation/scripts/build_task_to_episode_map.py \
  --dataset_dir /gpfs/home4/pkarageorgis/geo_octo/libero_datasets/libero_10_no_noops/1.0.0 \
  --out /gpfs/home4/pkarageorgis/geo_octo/evaluation/task_to_episode_map/libero_10_no_noops_1.0.0.json