#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=4
#SBATCH --gpus=1
#SBATCH --job-name=Evaluate_Octo
#SBATCH --ntasks=1
#SBATCH --time=05:30:00
#SBATCH --mem=8000M
#SBATCH --output=outfiles/evaluate_octo_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1
#module load CUDA/11.8.0


export WANDB_API_KEY="5d3260b21e8729601f20bfe817abc713a0dcc047"
export WANDB_ENTITY="nlp-squad"
export WANDB_PROJECT="Geo_Octo"


source activate octo-libero-eval

export CUDA_NVCC_BIN=$(python -c "import os,inspect,nvidia.cuda_nvcc as nvcc; print(os.path.join(os.path.dirname(inspect.getfile(nvcc)),'bin'))")
export NVRTC_LIB_DIR=$(python -c "import os,inspect,nvidia.cuda_nvrtc as nvrtc; print(os.path.join(os.path.dirname(inspect.getfile(nvrtc)),'lib'))")
export PATH="$CUDA_NVCC_BIN:$PATH"
export LD_LIBRARY_PATH="$NVRTC_LIB_DIR:$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
export PYTHONPATH="/gpfs/home4/pkarageorgis/geo_octo:/gpfs/home4/pkarageorgis/geo_octo/LIBERO:/gpfs/home4/pkarageorgis/geo_octo/octo:$PYTHONPATH"
export MUJOCO_GL=egl
export TOKENIZERS_PARALLELISM=false
export TF_CPP_MIN_LOG_LEVEL=3
export DISABLE_LIBERO_FLIPS=0

echo "--> Checking for NVIDIA driver with nvidia-smi:"
nvidia-smi
echo ""

# GPU diagnostics (runs on the allocated GPU node)
srun -n 1 python - <<'PY'
import os, jax, torch
print('CUDA_VISIBLE_DEVICES=', os.environ.get('CUDA_VISIBLE_DEVICES'))
print('JAX:', jax.default_backend(), jax.devices())
print('Torch CUDA:', torch.version.cuda)
PY

# # sanity checks
# ls -ld /gpfs/home4/pkarageorgis/geo_octo/evaluation/scripts/offline_regression.py
# ls -ld /gpfs/home4/pkarageorgis/geo_octo/octo/my_octo_vggt_model_offline/octo_vggt_finetune_staged/experiment_20250808_130401_BASELINE_RUN

# # Offline regression (override data root if needed)
# srun python -u /gpfs/home4/pkarageorgis/geo_octo/evaluation/scripts/offline_regression.py \
#   --model_path /gpfs/home4/pkarageorgis/geo_octo/octo/my_octo_vggt_model_offline/octo_vggt_finetune_staged/experiment_20250808_130401_BASELINE_RUN \
#   --batches 32 \
#   --batch_size 8 \
#   --config_string full,multimodal \
#   --data_root /gpfs/home4/pkarageorgis/geo_octo/libero_datasets

# # Parameter delta against HF base
# srun python -u /gpfs/home4/pkarageorgis/geo_octo/evaluation/scripts/check_param_delta.py \
#   --finetuned /gpfs/home4/pkarageorgis/geo_octo/octo/my_octo_vggt_model_offline/octo_vggt_finetune_staged/experiment_20250808_130401_BASELINE_RUN \
#   --base hf://rail-berkeley/octo-small-1.5 \
#   --topk 30

srun python -m evaluation.scripts.run_libero_eval \
  --model_family octo \
  --pretrained_checkpoint "/scratch-shared/tmp.cwkV8vOvfY/trained_models/my_octo_vggt_model_offline/octo_finetune_baseline/experiment_20251102_135224" \
  --task_suite_name libero_object \
  --checkpoint_step 200000 \
  --num_trials_per_task 1 \
  --num_open_loop_steps 4