#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1              # Request 4 GPUs instead of 1
#SBATCH --cpus-per-task=14        # Scale CPUs (3 GPUs × 7 CPUs)
#SBATCH --gpus=1                 # Request 4 GPUs
#SBATCH --job-name=Octo_Finetune_Offline_MultiGPU
#SBATCH --ntasks=1
#SBATCH --time=48:00:00
#SBATCH --mem=121000M             # Double the memory (or adjust as needed)
#SBATCH --output=outfiles/finetune_offline_octo_multigpu_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

export WANDB_API_KEY="5d3260b21e8729601f20bfe817abc713a0dcc047"
export WANDB_ENTITY="nlp-squad"
export WANDB_PROJECT="Geo_Octo"
export XLA_FLAGS="--xla_gpu_force_compilation_parallelism=1"
export TF_FORCE_GPU_ALLOW_GROWTH=true
export JAX_TRACEBACK_FILTERING=off
export TOKENIZERS_PARALLELISM=false

#export XLA_PYTHON_CLIENT_MEM_FRACTION=.7
#export XLA_PYTHON_CLIENT_PREALLOCATE=false
export JAX_PERSISTENT_CACHE_DISABLE=1
export JAX_DISABLE_PERSISTENT_CACHE=1

# Multi-GPU specific settings
# export CUDA_VISIBLE_DEVICES=0,1,2,3

source activate octo
cd octo

# srun -u python scripts/finetune_vggt.py \
#     --config=scripts/configs/config_vggt.py:full,language_conditioned \
#     --config.pretrained_path=hf://rail-berkeley/octo-base-1.5 \
#     --config.save_dir=./my_octo_vggt_model_offline

# RESUME CODE
srun -u python scripts/finetune_baseline.py \
  --config=scripts/configs/config_baseline.py:full,language_conditioned \
  --config.pretrained_path=/home/pkarageorgis/geo_octo/octo/my_octo_vggt_model_offline/octo_finetune_baseline/experiment_20250823_115519_SPATIAL_NO_VGGT \
  --config.pretrained_step=150000 \
  --config.save_dir=/home/pkarageorgis/geo_octo/octo/my_octo_vggt_model_offline \
  --config.resume_dir="/home/pkarageorgis/geo_octo/octo/my_octo_vggt_model_offline/octo_finetune_baseline/experiment_20250823_115519_SPATIAL_NO_VGGT" \
  --config.num_steps=250000 \
  --config.optimizer.learning_rate.decay_steps=250000