#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gres=gpu:1              # Request 4 GPUs instead of 1
#SBATCH --cpus-per-task=1        # Scale CPUs (4 GPUs × 7 CPUs)
#SBATCH --gpus=1                 # Request 4 GPUs
#SBATCH --job-name=Create_Stats
#SBATCH --ntasks=1
#SBATCH --time=05:30:00
#SBATCH --mem=48000M             # Double the memory (or adjust as needed)
#SBATCH --output=outfiles/unified_stats_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate octo
cd octo

srun python scripts/create_unified_statistics.py